/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const { forwardRef } = props
  const { nodes, materials } = useGLTF('/3d/models/Cherry.glb')
  return (
    <group ref={forwardRef} {...props}>
      <mesh material={materials.red} geometry={nodes.Icosphere.geometry} />
      <mesh material={materials.brown} geometry={nodes.Icosphere_1.geometry} />
    </group>
  )
}

useGLTF.preload('/3d/models/Cherry.glb')
